### ISSUE TITLE
Idle performance

### ISSUE THREAD

**Issue by keimpema** [marcoCasamento/Hangfire.Redis.StackExchange#35] opened 2016-11-30 10:31 UTC
I am seeing 20% cpu usage when Hangfire server is idle when I use Hangfire.Redis.StackExchange. It stays at 0% when using SqlServerStorage. There are no jobs running. Maybe there is a tight loop somewhere?

I am using MSOpenTech Redis for Windows 3.0.504 and nuget packages:
```
  <package id="Hangfire" version="1.6.7" targetFramework="net462" />
  <package id="Hangfire.Core" version="1.6.7" targetFramework="net462" />
  <package id="Hangfire.Redis.StackExchange" version="1.6.7.3" targetFramework="net462" />
  <package id="Hangfire.SimpleInjector" version="1.3.0.0" targetFramework="net462" />
  <package id="Hangfire.SqlServer" version="1.6.7" targetFramework="net462" />
  <package id="StackExchange.Redis" version="1.1.608" targetFramework="net462" />

```

Sql Server setup in startup.cs:

```
            Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage("Data Source=(localdb)\\ProjectsV13;Initial Catalog=Hangfire;Integrated Security=true;");
            Hangfire.GlobalConfiguration.Configuration.UseActivator(new SimpleInjectorJobActivator(container));
            app.UseHangfireServer();

```

Redis setup:

```
            var storage = new RedisStorage("localhost:6379, allowAdmin=true", new RedisStorageOptions { Db = 3 });
            Hangfire.GlobalConfiguration.Configuration.UseStorage(storage);
            Hangfire.GlobalConfiguration.Configuration.UseActivator(new SimpleInjectorJobActivator(container));
            app.UseHangfireServer();

```

VS performance monitor reports:

Redis
![profilingreportredis](https://cloud.githubusercontent.com/assets/943820/20748853/2e799754-b6f0-11e6-9b5a-d13e9ad4ac79.png)

SqlServer
![profilingreportsqlserver](https://cloud.githubusercontent.com/assets/943820/20748859/340cc4a2-b6f0-11e6-84dd-0c5979400d66.png)

**Comment by marcoCasamento** [comment] 2016-11-30 11:15
Thanks for signaling in such details.
I believe that the problem is inside https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/master/Hangfire.Redis.StackExchange/RedisSubscription.cs#L28.

If you're in a hurry you could try to temporarily add:
`cancellationToken.WaitHandle.WaitOne(TimeSpan.FromMinutes(3));`
at the end of the Execute method, or you could alo try to rollback to 1.6.5. 
Hope to carefully look at it this evening

**Comment by marcoCasamento** [comment] 2016-11-30 16:18
@keimpema any news on this ? did you try something of the above ?
I'd also like if @WebApelsin could give his insight on this

**Comment by WebApelsin** [comment] 2016-11-30 21:05
Yep, i think this could cause an idle load. The `RedisSubscription` as `IServerComponent` is wrapping in a loop inside the `BackgroundProcessingServer`. The proposed solution from @marcoCasamento should help. 

On the other hand, we are using this version on the production server under high load and I can't see such issue. Probably, it depends on the used hardware.

**Comment by keimpema** [comment] 2016-11-30 21:11
I also tried nuget packages:
 1.6.6.42 - same problem
 1.6.5.24 - no problem at all

**Comment by keimpema** [comment] 2016-11-30 22:01
The 3 minute wait at the beginning of the Execute method works. I was wondering why 3 minutes though? Seems a bit long.

**Comment by marcoCasamento** [comment] 2016-11-30 22:37
3 minutes it's totally arbitrary, just a wait long enough to don't cause problems.
Every IServerComponent run the execute method in an infinite loop driven by hangfire engine.
It's responsibility of the IServerComponent to pause in the exec in order to don't spike loads.
RedisSubscription Implements IServerComponent to get notified of the server shutdown and free resources on Redis server Instance.

Putting it at the beginning of the method, as suggested by WebApelSin is the correct place, and no timeout (wait for ever) should be better than the 3 minutes.
I'm trying this solution right now, to make sure that the Unsubscribe is called correctly (don't know how to unit test this!) then I'll push the fix.

Finally, I'd like to find a better way to handle the ISubscriber.Unsubscribe, (that use a thread for himself) but didn't find a better way to do it than this one, suggested by WebApelsin last month.

**Comment by keimpema** [comment] 2016-12-01 10:24
Thanks for the quick fix!

**Comment by marcoCasamento** [comment] 2016-12-01 10:58
You welcome.
I believe that the RedisStorage have to become IDisposable, but that's the topic for another issue, I'm going to close this one.

**Closed by marcoCasamento** 2016-12-01 10:58 UTC

**Comment by qq1206676756** [comment] 2018-08-10 16:43
hello!
I am currently experiencing this problem, how can I solve it in the end?
